from setuptools import setup

setup(
    name='myTextClassifier',
    version='1.0',
    packages=['venv.lib.python3.6.site-packages.nltk', 'venv.lib.python3.6.site-packages.nltk.app',
              'venv.lib.python3.6.site-packages.nltk.ccg', 'venv.lib.python3.6.site-packages.nltk.sem',
              'venv.lib.python3.6.site-packages.nltk.tag', 'venv.lib.python3.6.site-packages.nltk.tbl',
              'venv.lib.python3.6.site-packages.nltk.chat', 'venv.lib.python3.6.site-packages.nltk.draw',
              'venv.lib.python3.6.site-packages.nltk.misc', 'venv.lib.python3.6.site-packages.nltk.stem',
              'venv.lib.python3.6.site-packages.nltk.test', 'venv.lib.python3.6.site-packages.nltk.test.unit',
              'venv.lib.python3.6.site-packages.nltk.test.unit.translate',
              'venv.lib.python3.6.site-packages.nltk.chunk', 'venv.lib.python3.6.site-packages.nltk.parse',
              'venv.lib.python3.6.site-packages.nltk.corpus', 'venv.lib.python3.6.site-packages.nltk.corpus.reader',
              'venv.lib.python3.6.site-packages.nltk.cluster', 'venv.lib.python3.6.site-packages.nltk.metrics',
              'venv.lib.python3.6.site-packages.nltk.twitter', 'venv.lib.python3.6.site-packages.nltk.classify',
              'venv.lib.python3.6.site-packages.nltk.tokenize', 'venv.lib.python3.6.site-packages.nltk.inference',
              'venv.lib.python3.6.site-packages.nltk.sentiment', 'venv.lib.python3.6.site-packages.nltk.translate',
              'venv.lib.python3.6.site-packages.click', 'venv.lib.python3.6.site-packages.flask',
              'venv.lib.python3.6.site-packages.flask.json', 'venv.lib.python3.6.site-packages.jinja2',
              'venv.lib.python3.6.site-packages.werkzeug', 'venv.lib.python3.6.site-packages.werkzeug.debug',
              'venv.lib.python3.6.site-packages.werkzeug.contrib', 'venv.lib.python3.6.site-packages.markupsafe',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='',
    author='constantin',
    author_email='',
    description='', install_requires=['flask', 'nltk']
)
